//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public int exam_id { get; set; }
        public Nullable<int> class_id_fk { get; set; }
        public Nullable<int> st_fk_id { get; set; }
        public Nullable<int> suubject_fk_id { get; set; }
        public Nullable<int> total_marks { get; set; }
        public Nullable<int> obtained_marks { get; set; }
        public Nullable<System.DateTime> current_datee { get; set; }
    
        public virtual tbl_class tbl_class { get; set; }
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
    }
}
