//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fee()
        {
            this.financials = new HashSet<financial>();
            this.financials1 = new HashSet<financial>();
        }
    
        public int fee_id { get; set; }
        public Nullable<int> admission_fee_rs { get; set; }
        public Nullable<int> st_fk_id { get; set; }
        public Nullable<int> class_fk_id { get; set; }
        public Nullable<int> suubject_fk_id { get; set; }
        public Nullable<int> Fee_structure_id { get; set; }
    
        public virtual tbl_class tbl_class { get; set; }
        public virtual Fee_structure Fee_structure { get; set; }
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<financial> financials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<financial> financials1 { get; set; }
    }
}
