//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class financial
    {
        public int financial_id { get; set; }
        public string pettycash { get; set; }
        public Nullable<int> net_profit { get; set; }
        public Nullable<int> loss { get; set; }
        public Nullable<int> fee_id { get; set; }
        public Nullable<int> salary_id { get; set; }
    
        public virtual fee fee { get; set; }
        public virtual fee fee1 { get; set; }
    }
}
