//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int inventory_id { get; set; }
        public string items_name { get; set; }
        public Nullable<int> items_quanitity { get; set; }
        public Nullable<int> items_price { get; set; }
    }
}
