//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maarkSheet
    {
        public int Mar_id { get; set; }
        public string sub_one { get; set; }
        public string Markob_subone { get; set; }
        public string totalMarks_subone { get; set; }
        public string sub_two { get; set; }
        public string Markob_sub_two { get; set; }
        public string totalMarks_sub_two { get; set; }
        public string sub_three { get; set; }
        public string Markobsub_three { get; set; }
        public string totalMarks_sub_three { get; set; }
        public string sub_four { get; set; }
        public string Markob_sub_four { get; set; }
        public string totalMarks_sub_four { get; set; }
        public string sub_five { get; set; }
        public string Markob_sub_five { get; set; }
        public string totalMarks_sub_five { get; set; }
        public string sub_six { get; set; }
        public string Markob_sub_six { get; set; }
        public string totalMarks_sub_six { get; set; }
        public string sub_seve { get; set; }
        public string Markob_sub_seve { get; set; }
        public string totalMarks_sub_seve { get; set; }
        public string sub_eight { get; set; }
        public string Markob_sub_eight { get; set; }
        public string totalMarks_sub_eight { get; set; }
        public string sub_nine { get; set; }
        public string Markob_sub_nine { get; set; }
        public string totalMarks_sub_nine { get; set; }
        public string sub_ten { get; set; }
        public string Markob_sub_ten { get; set; }
        public string totalMarks_sub_ten { get; set; }
        public string total { get; set; }
        public string percentage { get; set; }
        public Nullable<System.DateTime> currentDate { get; set; }
        public Nullable<int> Stu_id { get; set; }
        public Nullable<int> Class_id { get; set; }
        public Nullable<int> Subject_id { get; set; }
    
        public virtual tbl_class tbl_class { get; set; }
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
    }
}
