//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staf_salary
    {
        public int Us_id { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string currMonth { get; set; }
        public string monthly_salary { get; set; }
        public string Bonus { get; set; }
        public string extra_Amount { get; set; }
        public Nullable<int> Staff_id { get; set; }
    
        public virtual tbl_staff tbl_staff { get; set; }
    }
}
