//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faculty_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_faculty_details()
        {
            this.timetables = new HashSet<timetable>();
            this.faculty_salary = new HashSet<faculty_salary>();
        }
    
        public int faculty_Id { get; set; }
        public string facullty_name { get; set; }
        public string father_name { get; set; }
        public string cnic { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string marital_status { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public string addresss { get; set; }
        public string qualification { get; set; }
        public string instituion { get; set; }
        public string experience { get; set; }
        public string descriptionn { get; set; }
        public string skill_activities { get; set; }
        public string faculty_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable> timetables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<faculty_salary> faculty_salary { get; set; }
    }
}
