//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_student()
        {
            this.exams = new HashSet<exam>();
            this.fees = new HashSet<fee>();
            this.maarkSheets = new HashSet<maarkSheet>();
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int stu_id { get; set; }
        public string applicant_name { get; set; }
        public string father_name { get; set; }
        public string father_occupation { get; set; }
        public string home_address { get; set; }
        public string email { get; set; }
        public string father_student_Cnic { get; set; }
        public string cell { get; set; }
        public string name_of_college { get; set; }
        public string stu_image { get; set; }
        public string groupp { get; set; }
        public Nullable<System.DateTime> date_of_admission { get; set; }
        public Nullable<System.DateTime> date_of_payment { get; set; }
        public Nullable<int> class_fk_id { get; set; }
        public Nullable<int> suubject_fk_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam> exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee> fees { get; set; }
        public virtual tbl_class tbl_class { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maarkSheet> maarkSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
    }
}
