//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int timetable_id { get; set; }
        public Nullable<int> class_id_fk { get; set; }
        public Nullable<int> faculty_id_fk { get; set; }
        public Nullable<int> suubject_fk_id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string dayss { get; set; }
    
        public virtual tbl_class tbl_class { get; set; }
        public virtual tbl_faculty_details tbl_faculty_details { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
    }
}
