//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coachingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cmsEntities : DbContext
    {
        public cmsEntities()
            : base("name=cmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<exam> exams { get; set; }
        public virtual DbSet<fee> fees { get; set; }
        public virtual DbSet<Fee_structure> Fee_structure { get; set; }
        public virtual DbSet<financial> financials { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<library> libraries { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_class> tbl_class { get; set; }
        public virtual DbSet<tbl_faculty_details> tbl_faculty_details { get; set; }
        public virtual DbSet<tbl_staff> tbl_staff { get; set; }
        public virtual DbSet<tbl_student> tbl_student { get; set; }
        public virtual DbSet<tbl_subject> tbl_subject { get; set; }
        public virtual DbSet<timetable> timetables { get; set; }
        public virtual DbSet<faculty_salary> faculty_salary { get; set; }
        public virtual DbSet<Staf_salary> Staf_salary { get; set; }
        public virtual DbSet<maarkSheet> maarkSheets { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
    }
}
